name: Setup node and pnpm
description: >
  Configures devbox, node, pnpm, cache, performs pnpm install

inputs:
  pnpm-run-install:
    description: Whether to run pnpm install
    required: false
    default: "true"
  pnpm-restore-cache:
    description: Whether to restore cache
    required: false
    default: "true"
  pnpm-install-cache-key:
    description: The cache key for the pnpm install cache
    required: false
    default: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}

runs:
  using: composite
  steps:
    - name: devbox installer
      uses: jetify-com/devbox-install-action@8c6a66ed6273138b1915457069de78cb52fe3bd7 # v0.15.0
      with:
        devbox-version: 0.17.3
        enable-cache: true

    - name: Get pnpm store path
      if: ${{ inputs.pnpm-restore-cache == 'true' }}
      id: pnpm-path
      shell: bash
      run: echo "STORE_PATH=$(devbox run pnpm store path)" >> $GITHUB_OUTPUT

    - name: Restore pnpm install cache
      if: ${{ inputs.pnpm-restore-cache == 'true' }}
      uses: actions/cache/restore@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      id: cache-restore
      with:
        path: |
          ${{ steps.pnpm-path.outputs.STORE_PATH }}
          ${{ github.workspace }}/.next/cache
        key: ${{ inputs.pnpm-install-cache-key }}
        restore-keys: |
          ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}-

    - name: Run pnpm install
      if: ${{ inputs.pnpm-run-install == 'true' }}
      shell: bash
      run: >
        devbox run
        pnpm install --frozen-lockfile

    - name: Save pnpm install cache
      if: ${{ inputs.pnpm-restore-cache == 'true' && steps.cache-restore.outputs.cache-hit != 'true' }}
      uses: actions/cache/save@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
      with:
        path: |
          ${{ steps.pnpm-path.outputs.STORE_PATH }}
          ${{ github.workspace }}/.next/cache
        key: ${{ inputs.pnpm-install-cache-key }}
