merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: dep-update
    autoqueue: true
    batch_max_wait_time: 30 min
    queue_conditions: &ref_conditions
      - author=renovate[bot]
      - check-success=amd64
      - check-success=build
      - check-success=codeql (actions)
      - check-success=codeql (javascript)
      - check-success=codeql (typescript)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success=playwright-tests
      - check-success=pr-title
      - check-success=renovate
      - check-success=smoke-test
      - check-success=types
      - check-success=unit-testing
      - check-success=zizmor
      - or:
          - check-success=renovate/stability-days
          - check-pending!=renovate/stability-days
    merge_conditions: *ref_conditions

pull_request_rules:
  - name: automatic approval
    conditions:
      - author!=renovate[bot]
      - check-success=amd64
      - check-success=build
      - check-success=codeql (actions)
      - check-success=codeql (javascript)
      - check-success=codeql (typescript)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success=playwright-tests
      - check-success=pr-title
      - check-success=renovate
      - check-success=smoke-test
      - check-success=types
      - check-success=unit-testing
      - check-success=zizmor
    actions:
      review:
        type: APPROVE
        message: "Automatically approving {{ author }}"

  - name: automatic approval for Renovate pull requests
    conditions:
      - author=renovate[bot]
      - check-success=amd64
      - check-success=build
      - check-success=codeql (actions)
      - check-success=codeql (javascript)
      - check-success=codeql (typescript)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success=playwright-tests
      - check-success=pr-title
      - check-success=renovate
      - check-success=smoke-test
      - check-success=types
      - check-success=unit-testing
      - check-success=zizmor
      - or:
          - check-success=renovate/stability-days
          - check-pending!=renovate/stability-days
    actions:
      review:
        type: APPROVE
        message: Automatically approving renovate

  - name: Automatically merge when GitHub Actions jobs succeed
    conditions:
      - author!=renovate[bot]
      - check-success=amd64
      - check-success=build
      - check-success=codeql (actions)
      - check-success=codeql (javascript)
      - check-success=codeql (typescript)
      - check-success=dependency-review
      - check-success=format
      - check-success=gitleaks
      - check-success=lint
      - check-success=playwright-tests
      - check-success=pr-title
      - check-success=renovate
      - check-success=smoke-test
      - check-success=types
      - check-success=unit-testing
      - check-success=zizmor
      - "#approved-reviews-by>=1"
      - or:
          - check-success=renovate/stability-days
          - check-pending!=renovate/stability-days
    actions:
      merge:
        method: merge

  - name: Automatically queue Renovate PRs
    conditions:
      - author=renovate[bot]
    actions:
      queue:

  - name: Ask Renovate to rebase when out of date
    conditions:
      - author=renovate[bot]
      - queue-name=dep-update
      - queue-position=0
      - "#commits-behind > 0"
    actions:
      label:
        add:
          - rebase

  - name: automatic deletion of head branch after merge
    conditions:
      - merged
    actions:
      delete_head_branch:
