services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.31.0@sha256:f1e548c20c99d2678744be9d90955c0ab208ecc273db2a7a0b5dc5673d0b57fd
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"

  web:
    build:
      context: ./
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "3000:3000"
    healthcheck:
      test:
        - CMD
        - node
        - "--eval"
        - '"fetch(''http://0.0.0.0:3000/api/health'').then(r => process.exit(r.status === 200 ? 0 : 1))"'
      start_interval: 5s
      start_period: 5s
