services:
  otel-lgtm:
    image: grafana/otel-lgtm:0.27.1@sha256:f533fb9c059aad2d47658e9dc059289755d992404b62168b40b3fbcbe4623355
    ports:
      - "4000:3000"
      - "4317:4317"
      - "4318:4318"
    restart: "no"

  web:
    build:
      context: ./
    develop:
      watch:
        - action: rebuild
          path: .
    ports:
      - "3000:3000"
    healthcheck:
      test:
        - CMD
        - node
        - "--eval"
        - '"fetch(''http://0.0.0.0:3000/api/health'').then(r => process.exit(r.status === 200 ? 0 : 1))"'
      start_interval: 5s
      start_period: 5s
