allowBuilds:
  esbuild: false
  lefthook: true
  msw: false
  protobufjs: false
  sharp: false

# enableGlobalVirtualStore: true

hoistPattern: []

# Only install package versions published at least 3 days ago
minimumReleaseAge: 4320

savePrefix: ""

sideEffectsCache: false
