name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

env:
  LEFTHOOK: 0

permissions: {}

jobs:
  playwright-test-dev:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-dev
      cancel-in-progress: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Run Playwright tests (dev)
        shell: devenv shell bash -- -e {0}
        run: pnpm exec playwright test --reporter html

      - name: Upload HTML report (dev)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: html-report-dev--attempt-${{ github.run_attempt }}
          path: playwright-report/
          retention-days: 7

  playwright-test-prod:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-prod
      cancel-in-progress: true
    steps:
      - name: Git Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Run Playwright tests (prod)
        shell: devenv shell bash -- -e {0}
        run: pnpm exec playwright test --config playwright.prod.config.ts --reporter html

      - name: Upload HTML report (prod)
        if: ${{ !cancelled() }}
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: html-report-prod--attempt-${{ github.run_attempt }}
          path: playwright-report/
          retention-days: 7
