name: Unit testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions:
  contents: read

jobs:
  unit-testing:
    runs-on: ubuntu-24.04
    permissions:
      # Write permissions for pull-requests are required for creating the Jest coverage comment, comment out if you aren't using this option
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Unit & Integration tests
        run: pnpm test --coverage --coverageReporters json-summary --show-seed
        env:
          FORCE_COLOR: 1

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@aa3935cf9ee61efc40d9e47dcc8a523a49a70b96 # v1.0.28
