name: Unit testing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  LEFTHOOK: 0

permissions:
  contents: read

jobs:
  unit-testing:
    runs-on: ubuntu-24.04
    permissions:
      # Write permissions for pull-requests are required for creating the Jest coverage comment, comment out if you aren't using this option
      pull-requests: write
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@002fdce3c6a235733a90a27c80493a3241e56863 # v2.12.1
        with:
          egress-policy: audit

      - name: Git Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Node setup
        uses: ./.github/actions/setup

      - name: Unit & Integration tests
        run: pnpm test --coverage --coverageReporters json-summary
        env:
          FORCE_COLOR: 1

      - name: Jest Coverage Comment
        uses: MishaKav/jest-coverage-comment@d74238813c33e6ea20530ff91b5ea37953d11c91 #v1.0.27
